### ISSUE TITLE
Needs Update 6.0

### ISSUE THREAD

**Issue by DiggityMan420** [PrincessRTFM/MyDalamudPlugins#1]
"XiV Combo Very Expanded" Plugin Not showing up as updated to 6.0 and plans to do so

**Comment by PrincessRTFM** [comment]
Yes, it will be updated. Unfortunately, given current server queue times, just getting into the game to _look_ at new actions is very slow.

Updating this plugin after such a massive game update has three stages:
- Update to the latest Dalamud API so it compiles
- Make sure the signatures are all right so it _works_
- Go over actions and combos to see what needs to be updated and added

**Comment by PrincessRTFM** [comment]
The `v3.0.0b` public beta release is now available and will be in the plugin installer, provided you have the custom repo URL added. Nothing is yet implemented for Sage, but if you have suggestions/requests, feel free to open an issue about them with a _clear and detailed_ explanation of how you want it to work, including what button(s) should be affected, what they should turn into, and under what conditions the replacements should occur.

If any of the existing combos act weird, open a bug report for them too. Experimental ones are the ones that _I_ feel are most likely to have misbehaviour bugs, but YMMV. There's one Monk combo marked unsafe as well; if this crashes you, report it so it can be disabled. No other combos _should_ cause crashes, but that one does something unusual to work right now.
